<?php
session_start(); // starting user session
// Pulled from Chizzy's Branch

//require_once('../rabbitMQ/RabbitMQServer.php');
require_once('../rabbitMQ/rabbitMQLib.inc');
require_once('../rabbitMQ/send.php');


if (!isset($_POST['username']) || !isset($_POST['password'])) {
            echo json_encode(["error" => "Missing username or password"]);
            exit(0);
}


$request = $_POST;
$response = "Unsupported Request. Denied!"; // failed request

switch ($request['type'] ?? '') { // ternary thingy; checks if string is set. If not, it makes sure its empty so it can throw an error.
    case 'login':
        //creating variables to hold the username and the password
        // Accepts either username/password (our AJAX) our username/password just in case
        $username = $request['username'] ?? ($request['username'] ?? ''); // same ternary thing
        $password = $request['password'] ?? ($request['password'] ?? '');

        //If the client returns an empty string for the username or the password, then the login fails

        if ($username === '' || $password === '') { // triple equal sign is like == but is more strict/case sensitive
            $response = "Login Failed: Missing credentials";
            break;
        }

        try {
            // Sending the login request to RabbitMQ on the database listener
            // Im not sure but do we have  to create a request queue and a response queue, this being sent to the request queue, or leave it for simplicity?
            $request   = [
                'action' => 'login', 
                'username' => $username, 
                'password' => $password
            ];
                //the request array being built
            $response  = $connection->send_request ($request);  // response 
            // sendRequest is a function in RabbitMQClient.php
            //  Building message to send to the RabbitMQ server

            if (is_array($response) && ($response['status'] ?? '') === 'success') { // handling the response back from the rabbit mq server if the login was succesful
                //if the rmq response sent back is an array and the status is success then we set the session variables
                $_SESSION['login']       = true;// setting the session varibables
                $_SESSION['username']       = $username;
                $_SESSION['session_key'] = $response['session_key'] ?? null;//storing session key if one was returned (it will be created/generated by the db listener)
                
                $response = "Login Success."; 
            } else {//failed login
                $msg = is_array($response) ? ($response['message'] ?? 'Invalid credentials') : 'No response';
                $response = "Login Failed: " . $msg;
            }
        } catch (Exception $e) {
            $response = "Login Failed: " . $e->getMessage();
        }
        break;
}

echo json_encode($response);
exit(0);
